"""
Build results/tables/defense_watermark.tex from the JSONs in
results_defense_watermark/.

Reads all summary.json files under DEFAULT_RESULTS_ROOT, groups by
(scenario, eps), and emits a single LaTeX tabular fragment plus a small
caption suitable for `\input` from defense.tex.

Optionally pulls in the existing eps=0.3 / eps=0.5 / eps=10 christmas_jazz_1
results from 6_results_watermark_saycan/ for the S3 eps-sweep rows so you do
not need to re-run them.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import EVAL_ROLLUPS_DIR, PROJECT_ROOT

ROOT = Path(PROJECT_ROOT)
# Reference rollups ship in data/eval_rollups/; generated .tex goes to results/tables/.
ROLLUPS = Path(EVAL_ROLLUPS_DIR)
TABLES_OUT = ROOT / "results" / "tables"
CODEC = ROOT
DEFAULT_RESULTS_ROOT = ROLLUPS / "_results_watermark"
TEX_OUT = TABLES_OUT / "defense_watermark.tex"
LEGACY_SAYCAN = ROLLUPS / "_results_watermark" / "saycan_attack_detection"

SCEN_LABEL = {
    "s1": "S1 finance (EN speech)",
    "s2": "S2 interview (EN speech)",
    "s3": "S3 music (christmas\\_jazz)",
}

MODEL_LABEL = {
    "qwen2_audio":    "Qwen2-Audio",
    "qwen25_omni":    "Qwen2.5-Omni",
    "audio_flamingo": "AudioFlamingo3",
}


def _load_summary(path: Path) -> Optional[dict]:
    try:
        return json.loads(path.read_text())
    except Exception as e:
        print(f"  skip {path}: {e}")
        return None


def _legacy_saycan_rows() -> List[dict]:
    """Pull in eps=0.3 / 0.5 / 10 christmas_jazz_1 SayCan numbers from the
    pre-existing experiment, so the paper table can show the eps sweep without
    requiring three more attack runs."""
    rows: List[dict] = []
    if not LEGACY_SAYCAN.is_dir():
        return rows
    # The legacy layout has subdirs named eps{eps}_christmas_jazz_1/results.json
    # plus a top-level results.json from the very first eps=10 run.
    candidates = list(LEGACY_SAYCAN.glob("*/results.json")) + [LEGACY_SAYCAN / "results.json"]
    for p in candidates:
        if not p.is_file():
            continue
        d = _load_summary(p)
        if not d or d.get("experiment") != "attack_detection":
            continue
        s = d.get("summary", {})
        if not s:
            continue
        eps = float(d.get("eps", 0.0))
        n = s.get("total_pairs", 0)
        rows.append({
            "scenario": "s3",
            "target_model": "qwen2_audio",  # legacy results were Qwen2-Audio only
            "eps": eps,
            "n_total": n,
            "attack_success_rate": s.get("attack_success_rate", 0.0),
            "destruction_rate": s.get("defense_rate", 0.0),
            "avg_clean_detection_score": s.get("avg_clean_score", 0.0),
            "avg_adv_detection_score": s.get("avg_adversarial_score", 0.0),
            "source": "legacy",
        })
    # Dedupe by (scenario, model, eps), preferring the largest n.
    by_key: Dict[tuple, dict] = {}
    for r in rows:
        k = (r["scenario"], r.get("target_model", "qwen2_audio"), round(r["eps"], 4))
        if k not in by_key or by_key[k]["n_total"] < r["n_total"]:
            by_key[k] = r
    return list(by_key.values())


def collect_rows(results_root: Path, include_legacy: bool) -> List[dict]:
    rows: List[dict] = []
    if results_root.is_dir():
        for sd in sorted(results_root.iterdir()):
            sp = sd / "summary.json"
            if not sp.is_file():
                continue
            d = _load_summary(sp)
            if not d or d.get("experiment") != "attack_detection":
                continue
            d["source"] = "new"
            rows.append(d)
    if include_legacy:
        # Skip legacy rows that are already present at the same (scenario, eps).
        existing = {(r.get("scenario"), round(r.get("eps", 0.0), 4)) for r in rows}
        for lr in _legacy_saycan_rows():
            if (lr["scenario"], round(lr["eps"], 4)) not in existing:
                rows.append(lr)
    # Sort: s1 < s2 < s3, then by model, then by eps ascending
    scen_order = {"s1": 0, "s2": 1, "s3": 2}
    model_order = {"qwen2_audio": 0, "qwen25_omni": 1, "audio_flamingo": 2}
    rows.sort(key=lambda r: (
        scen_order.get(r.get("scenario"), 9),
        model_order.get(r.get("target_model", "qwen2_audio"), 9),
        r.get("eps", 0),
    ))
    return rows


def render_latex(rows: List[dict], roundtrip_summary: Optional[dict]) -> str:
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/build_defense_table.py")
    lines.append("% Do not edit by hand. Regenerate via run_defense.sh option 7.")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    scen_set = sorted({r.get("scenario", "?") for r in rows})
    scen_phrase = ", ".join(SCEN_LABEL.get(s, s).split(" ")[0] for s in scen_set) if scen_set else "tested scenarios"
    cap_lines = [
        r"\caption{AudioSeal watermark detection under the latent attack on " + scen_phrase + "."
        r" ``WM Dest.'' = fraction of pairs whose post-attack AudioSeal detection score falls below the $0.5$ threshold."
        r" ``Adv Det.'' = mean detection score on the adversarial output (higher means the watermark survives)."
    ]
    if roundtrip_summary is not None:
        cap_lines.append(
            f" Codec round-trip control: {roundtrip_summary.get('n_survived',0)}/"
            f"{roundtrip_summary.get('n_total',0)} watermarks survive clean EnCodec encode--decode "
            f"({roundtrip_summary.get('survival_rate',0)*100:.0f}\\%), so destruction is attributable to "
            "the attack rather than the codec round-trip alone."
        )
    cap_lines.append("}")
    lines.append("".join(cap_lines))
    lines.append(r"\label{tab:defense_watermark}")
    lines.append(r"\begin{tabular}{lllrrrr}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Scenario} & \textbf{Model} & \textbf{$\epsilon$} & \textbf{$n$} & \textbf{ASR} & \textbf{WM Dest.} & \textbf{Adv Det.} \\")
    lines.append(r"\midrule")

    last_key = None
    for r in rows:
        scen = r.get("scenario", "?")
        scen_label = SCEN_LABEL.get(scen, scen)
        model = r.get("target_model", "qwen2_audio")
        model_label = MODEL_LABEL.get(model, model)
        eps = r.get("eps", 0.0)
        n = r.get("n_total", 0)
        asr = r.get("attack_success_rate", 0.0) * 100
        wmd = r.get("destruction_rate", 0.0) * 100
        adv = r.get("avg_adv_detection_score", 0.0)
        key = (scen, model)
        scen_cell = scen_label if (last_key is None or last_key[0] != scen) else ""
        model_cell = model_label if key != last_key else ""
        if last_key is not None and key != last_key:
            lines.append(r"\midrule")
        last_key = key
        lines.append(
            f"{scen_cell} & {model_cell} & {eps:.1f} & {n} & {asr:.1f}\\% & {wmd:.1f}\\% & {adv:.3f} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results-root", default=str(DEFAULT_RESULTS_ROOT))
    ap.add_argument("--out", default=str(TEX_OUT))
    ap.add_argument("--no-legacy", action="store_true",
                    help="Do not pull eps=0.3/0.5/10 christmas_jazz rows from 6_results_watermark_saycan/")
    args = ap.parse_args()

    results_root = Path(args.results_root)
    rows = collect_rows(results_root, include_legacy=not args.no_legacy)
    if not rows:
        print(f"No results found in {results_root} (and no legacy fallback).")
        return

    rt = None
    rt_path = results_root / "codec_roundtrip" / "summary.json"
    if rt_path.is_file():
        rt = _load_summary(rt_path)

    tex = render_latex(rows, rt)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(tex)
    print(f"Wrote {out}  ({len(rows)} rows)")
    print("\nPreview:")
    print(tex)


if __name__ == "__main__":
    main()
